[project]
name = "ss-pool"
version = "0.2.0"
description = "基于 sslocal( https://github.com/shadowsocks/shadowsocks-rust ) 的代理池"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = ["aiohttp>=3.12.15", "loguru>=0.7.3"]

[tool.setuptools]
packages = ["ss_pool"]
