[project]
name = "ss-pool"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "valkey[libvalkey]>=6.1.0",
]

[dependency-groups]
dev = [
    "patchright>=1.52.5",
    "playwright>=1.53.0",
]
