[project]
name = "ss-pool"
version = "0.1.5"
requires-python = ">=3.13"
dependencies = ["aiohttp>=3.12.14"]

[dependency-groups]
dev = [
    "colorama>=0.4.6",
    "loguru>=0.7.3",
    "patchright>=1.52.5",
    "playwright>=1.53.0",
]

[tool.setuptools]
packages = ["ss_pool"]
